name: movo
description: Movies application

publish_to: 'none'

version: 2.7.8

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # state
  get: ^4.7.2

  # network
  json_annotation: ^4.9.0
  retrofit: ^4.6.0
  dio: ^5.8.0+1

  # storage
  sqflite: ^2.4.2
  shared_preferences: ^2.5.3
  file_picker: ^10.2.0

  # helpers
  video_player: ^2.10.0
  wakelock_plus: ^1.3.2
  collection: ^1.19.1
  flutter_hooks: ^0.21.2
  visibility_detector: ^0.4.0+2
  permission_handler: ^12.0.1
  device_info_plus: ^11.5.0

  # di
  get_it: ^8.0.3
  injectable: ^2.5.0

  # ui
  rive: ^0.13.20
  flutter_svg: ^2.2.0
  fl_chart: ^1.0.0

  # firebase
  cloud_firestore: ^5.6.11
  firebase_core: ^3.15.1

  # i18n
  flutter_localizations:
    sdk: flutter

  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.5.4
  json_serializable: ^6.9.5
  injectable_generator: ^2.7.0
  freezed: ^3.1.0
  retrofit_generator: ^9.7.0
  logger: ^2.6.0
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/logo_filled.png'
  image_path_android: 'assets/logo.png'
  min_sdk_android: 19

  remove_alpha_ios: true
  adaptive_icon_background: '#ffffffff'
